AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  My SAM App

Resources:
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "pagename"
          AttributeType: "S"
       
      KeySchema: 
        - 
          AttributeName: "pagename"
          KeyType: "HASH"
      
      TableName: "visitor_counter"
      ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'www.rajanpanchal.com'"
    Auth:
     UsagePlan:
      CreateUsagePlan: PER_API
      Description: Usage plan for this API
      Quota:
       Limit: 500
       Period: MONTH
      Throttle:
       BurstLimit: 100
       RateLimit: 50
  CloudResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: getcounterscript.getCounter
      Runtime: python2.7
      Policies:
      # Give DynamoDB Full Access to your Lambda Function
      - AmazonDynamoDBFullAccess
      Events:
        getCounter:
          Type: Api
          Properties:
            Path: /getVisitorCounter
            Method: get
            RestApiId: !Ref ApiGatewayApi
